			INP
			STO DIVIDEND
			INP
			STO DIVISOR
			BRZ DIVERROR
DIVLOOP		LDA DIVIDEND
			SUB DIVISOR
			STO DIVIDEND
			LDA QUOTIENT
			ADD ONE
			STO QUOTIENT
			LDA DIVIDEND
			BRZ DIVPERFECT
			BRP DIVLOOP
			BRA DIVOVER
DIVOVER		LDA DIVIDEND
			ADD DIVISOR
			STO REMAINDER
			LDA QUOTIENT
			SUB ONE
			STO QUOTIENT
DIVPERFECT	LDA QUOTIENT
			OUT
			LDA REMAINDER
			OUT
			HLT
DIVERROR	LDA DIVISOR
			OUT
ONE			DAT 1
DIVIDEND	DAT 0
DIVISOR		DAT 0
QUOTIENT	DAT 0
REMAINDER	DAT 0