BRA					DATA_REQUEST
F_MULTIPLY			LDA ZERO
					STO F_MULTIPLY_RESULT
F_MULTIPLY_LOOP		LDA F_MULTIPLY_A
					BRZ F_MULTIPLY_END
					SUB ONE
					STO F_MULTIPLY_A
					LDA F_MULTIPLY_RESULT
					ADD F_MULTIPLY_B
					STO F_MULTIPLY_RESULT
					LDA F_MULTIPLY_A
					BRP F_MULTIPLY_LOOP
F_MULTIPLY_END		LDA ZERO
					STO F_MULTIPLY_A
					STO F_MULTIPLY_B
					LDA F_MULTIPLY_RETADDR
					BRA ACC
DATA_REQUEST		INP
					BRZ END
					STO F_MULTIPLY_A
					INP
					BRZ END
					STO F_MULTIPLY_B
					BRA F_MULTIPLY
DATA_OUT			LDA F_MULTIPLY_RESULT
					OUT
					LDA NEW_LINE
					OTC
					BRA DATA_REQUEST
END					HLT
ZERO				DAT 0
ONE					DAT 1
F_MULTIPLY_RESULT	DAT 0
F_MULTIPLY_A		DAT 0
F_MULTIPLY_B		DAT 0
F_MULTIPLY_RETADDR	DAT 24
NEW_LINE			DAT 10